# -*- coding: utf-8 -*-
"""Chapter Four: Objective Two."""
import json
B = []
def H2(t): B.append(dict(k='h2', t=t))
def H3(t): B.append(dict(k='h3', t=t))
def P(t):  B.append(dict(k='p', t=t))
def TB(n, title): B.append(dict(k='table', n=n, t=title))
def FG(n, t, f, note): B.append(dict(k='fig', n=n, t=t, f=f, note=note))

H2('4.4 Objective Two: Functions Performed by Actors at Each Market Node')
P('Objective Two examined what each actor category actually does with a mud crab: how it is obtained, prepared, graded, packed, moved, priced and paid for. The results are grouped into acquisition and disposal, buyers and market channels, handling and transport, grading and quality, losses, payment and price setting, trading relationships, and reported prices.')

H3('4.4.1 Acquisition of Crabs and Disposal of the Catch')
TB(16, 'How Mud Crabs Are Acquired and Source of Crabs for Sale by Actor and BMU')
P('Table 16 divides the chain at its first joint. Every fisher obtained crabs by catching them and every middleman, hotelier and exporter obtained them by purchase, with no exception at any site. Source of crabs followed the same division: all 65 fishers caught personally, 21 of 22 middlemen (95.5%) purchased from other middlemen, all five hoteliers purchased from middlemen, and all four exporters purchased from middlemen or agents. The single middleman who caught personally was at Shimoni.')
FG(12, 'Source of Crabs for Sale Within Each Actor Category', 'f07_sourcing_actor',
   'Bars show the percentage within each actor category. Percentages are valid percentages within the actor category.')
TB(17, 'Fishing or Collection Gear Used by Actor and BMU')
P('Table 17 covers harvesting gear, an item answered by fishers and by the one middleman who also caught. Hand collection dominated (47 of 65, 72.3%), ranging from 8 (57.1%) at Majoreni to 2 (100.0%) in the Other sites group. Scoop nets accounted for 9 (13.8%) and hooked sticks for 8 (12.3%), with a single report of sweep nets. Gear was not associated with BMU (p = .144).')
FG(13, 'Fishing or Collection Gear Used by Fishers Within Each BMU', 'f30_gear_site',
   'Bars show the percentage of fishers within each BMU. Hand collection was the dominant method at all four sites.')
TB(18, 'Daily Mud Crab Catch Reported by Actor and BMU')
P('As shown in Table 18, the most commonly reported daily catch was 5–10 kg (44 of 65 fishers, 67.7%), a share ranging from 8 (57.1%) at Majoreni to 17 (81.0%) at Vanga. Catches above 10 kg were reported by 14 fishers (21.5%) and catches of 4–5 kg by 6 (9.2%), the latter concentrated at Msambweni (1, 33.3%). Daily catch was not associated with BMU (p = .453). The item was not put to middlemen, hoteliers or exporters, whose columns are therefore blank.')
FG(14, 'Daily Mud Crab Catch Reported by Fishers Within Each BMU', 'f31_catch_site',
   'Bars show the percentage of fishers within each BMU. The 5–10 kg band was the most common at every site.')
TB(19, 'Proportion of Catch Sold and Travel Time from Fishing Grounds to Market by Actor and BMU')
P('Table 19 reports what fishers did with the catch and how far they had to carry it. Selling the whole catch was the norm (52, 80.0%), ranging from 2 (66.7%) at Msambweni to 13 (92.9%) at Majoreni; the remaining 13 fishers (20.0%) sold three-quarters. Travel time to market was six hours for 43 fishers (66.2%) and one hour for 22 (33.8%). Travel time varied significantly by site (p = .010): 21 of 25 Shimoni fishers (84.0%) and all three at Msambweni reported six hours, against only 5 of 14 at Majoreni (35.7%). Proportion sold was not associated with BMU (p = .452).')
FG(15, 'Travel Time from Fishing Grounds to Market, Fishers by BMU', 'f32_traveltime_site',
   'Bars show the percentage of fishers within each BMU. Majoreni fishers reached the point of sale considerably faster than fishers elsewhere.')
P('Tables 16 to 19 establish the harvesting node as a seller with no holding capacity and no alternative to immediate sale. A fisher who lands 5 to 10 kg of live crab, carries it on foot for up to six hours and disposes of the entire catch the same day has no practical means of waiting for a better offer. That the Majoreni fishers reached market fastest is worth carrying forward, because Majoreni also turns out to be the site where fishers received the best price.')

H3('4.4.2 Buyers and Market Channels')
TB(20, 'Main Buyer Category by Actor and BMU')
P('Table 20 shows who each actor sold to. Every fisher, at every site, sold to a first-level middleman. Middlemen sold on to company agents (9, 40.9%), second-level middlemen (7, 31.8%) or exporters (5, 22.7%), with one selling to another first-level middleman; the company-agent share ranged from 3 (27.3%) at Shimoni to 3 (75.0%) at Vanga, and buyer category was not associated with BMU (p = .656). Hoteliers sold to consumers and exporters to importers, in both cases without exception.')
FG(16, 'Main Buyer Category Within Each Actor Category', 'f08_buyer_actor',
   'Bars show the percentage within each actor category. Fishers sold exclusively to first-level middlemen; each downstream category had its own distinct main buyer.')
TB(21, 'Primary Market Channel and Contact With Final Consumers by Actor and BMU')
P('Table 21 completes the picture. Fishers and middlemen supplied local markets exclusively, hoteliers supplied restaurants and hotels, and exporters supplied export markets. Contact with the final consumer divided just as cleanly: all 65 fishers and all 22 middlemen reached the consumer only through intermediaries, while all five hoteliers and all four exporters dealt with the end buyer directly. Neither item varied enough within fishers or middlemen to support a test against BMU.')
P('Tables 20 and 21 answer a central part of Objective Two. The actors who know what a crab finally sells for are the two groups furthest from the water, and the two groups who catch and aggregate it never meet the person who eats it. That informational distance is the structural fact underlying the price results reported later in this chapter.')

H3('4.4.3 Preparation, Packaging and Transport')
TB(22, 'Preparation of Mud Crabs for Market and Preservation by Actor and BMU')
P('As shown in Table 22, preparation became more elaborate at each step. All 65 fishers prepared crabs by tying the claws; 21 of 22 middlemen (95.5%) cleaned, sorted and graded; all five hoteliers processed for the kitchen; and all four exporters cleaned, sorted and graded for consignment. Preservation was reported only by the hoteliers, all five of whom froze the product; no fisher, middleman or exporter preserved or processed at all. Preparation was not associated with BMU among middlemen (p = 1.000).')
FG(17, 'Preparation of Mud Crabs for Market by Actor Category', 'f09_preparation_actor',
   'Bars show the percentage within each actor category. Preparation moves from tying claws at the harvesting node to cleaning, sorting and grading downstream.')
TB(23, 'Packaging Used for Transporting Mud Crabs by Actor and BMU')
P('Table 23 shows a clear ladder of containment. Fishers used sacks (44, 67.7%) or plastic containers (21, 32.3%); middlemen used crates (11, 50.0%) or baskets (10, 45.5%), with one still using a sack; and all four exporters used Styrofoam. Hoteliers did not complete this item because they bought at their own premises, so their column is left blank rather than recorded as zero. Packaging was not associated with BMU for fishers (p = .837) or middlemen (p = .924).')
FG(18, 'Packaging Used for Transporting Mud Crabs by Actor Category', 'f10_packaging_actor',
   'Bars show the percentage within each actor category. Hoteliers did not complete this item because they purchased at their own premises.')
TB(24, 'Mode of Transporting Mud Crabs to Market by Actor and BMU')
P('Table 24 follows the same ladder. Fishers travelled on foot (57, 87.7%) or by motorcycle (8, 12.3%); middlemen used vehicles (17, 77.3%) or motorised boats (4, 18.2%), with one on foot; and all four exporters used air freight. Transport was not associated with BMU for fishers (p = .388) or middlemen (p = .402).')
FG(19, 'Mode of Transporting Mud Crabs to Market by Actor Category', 'f11_transport_actor',
   'Bars show the percentage within each actor category. Hoteliers did not complete this item.')
P('Tables 22 to 24 show that protection of the product rises with distance from the water, and that the cost of that protection is borne by whoever holds the crab at the time. A sack carried on foot and a Styrofoam box flown out are two ends of the same handling problem, and the actor least able to absorb a loss is the one using the least protective method.')

H3('4.4.4 Grading and Quality Control')
TB(25, 'Grading Practice and Criteria Used to Determine Grade by Actor and BMU')
P('Table 25 records the single most consequential functional difference in the chapter. Every one of the 96 respondents, at every site, said they graded mud crabs. They did not grade by the same rule. All 65 fishers graded on weight alone, while 21 of 22 middlemen (95.5%) and every hotelier and exporter combined size, weight, shell condition and claw size. The one middleman using weight alone was at Shimoni. Grading criteria did not vary by site among middlemen (p = 1.000), and did not vary at all among fishers.')
FG(20, 'Criteria Used to Determine Crab Grade by Actor Category', 'f12_grading_actor',
   'Bars show the percentage within each actor category. Fishers graded on weight alone; every other category used a four-criterion rule.')
TB(26, 'Quality Measures Before Market and Use of Formal Quality Control by Actor and BMU')
P('Table 26 shows the same asymmetry in quality assurance. Fishers tied the claws (65, 100.0%); middlemen (21, 95.5%) and hoteliers cited packaging standards; exporters cited inspections, certification and packaging standards. Formal quality-control measures were reported by all nine downstream actors and by none of the 87 fishers and middlemen.')
TB(27, 'Size Label and Grade Assignment for Large Crabs by Actor and BMU')
P('As shown in Table 27, 53 fishers (81.5%) used the Large label for their biggest crabs while 12 (18.5%) recorded all sizes or mixed, and 50 (76.9%) assigned Grade A while 15 (23.1%) assigned a mixed grade. Every middleman, hotelier and exporter who answered used the plain labels. The fisher pattern varied significantly by site (p = .001): at Shimoni only 14 of 25 (56.0%) used the Large label, against all 14 at Majoreni and 20 of 21 (95.2%) at Vanga.')
FG(21, 'Large-Crab Size Label Reported by Fishers Within Each BMU', 'f29_fisher_sizelabel_site',
   'Bars show the percentage of fishers within each BMU using each label. The Other sites group is excluded from the site comparison.')
TB(28, 'Size Label and Grade Assignment for Medium Crabs by Actor and BMU')
P('Table 28 shows a narrower spread for medium crabs. Sixty-three fishers (96.9%) used the Medium label and 51 (78.5%) assigned Grade B, against 14 (21.5%) who assigned a mixed grade. Every middleman and exporter used the plain labels. The medium-size label was not associated with BMU (p = .406). Hoteliers did not complete the medium-crab grading items.')
TB(29, 'Size Label and Grade Assignment for Small Crabs by Actor and BMU')
P('Table 29 covers the small grade, reported by fishers only. Fifty-six fishers (86.2%) used the Small label and 59 (90.8%) assigned Grade C, while 9 (13.8%) recorded mixed size and 6 (9.2%) a mixed grade. Small-size labelling varied significantly by site (p = .002), with 16 of 25 Shimoni fishers (64.0%) using the plain label against all fishers at Majoreni, Vanga and Msambweni.')
P('Tables 25 to 29 identify the mechanism by which value is captured downstream. A fisher can weigh a crab as accurately as anyone; what he cannot do is price the shell condition and claw size his buyer is paying for, or verify independently that the grade offered is the grade the animal deserves. The site variation in labelling compounds the problem. The survey recorded the word used, not a measured carapace width, so this is a matter of vocabulary rather than biology — but a Shimoni fisher and his buyer may not mean the same thing by the word large, and that is precisely the condition under which a grading dispute resolves in favour of the better-informed party.')

H3('4.4.5 Reported Losses')
TB(30, 'Reported Daily Mortality by Actor and BMU')
P('Table 30 shows that losses rise with the volume each actor holds. All 65 fishers reported daily mortality of 0.5 to 1 kg; 21 of 22 middlemen (95.5%) reported 4 to 5 kg; all four exporters reported more than 10 kg; and all five hoteliers reported no mortality because they froze the product on arrival. Mortality was not associated with BMU among middlemen (p = 1.000).')
FG(22, 'Reported Daily Mortality by Actor Category', 'f13_mortality_actor',
   'Bars show the percentage within each actor category. Hoteliers reported no mortality because crabs were frozen on arrival.')
TB(31, 'Reported Loss Through Spoilage by Actor and BMU')
P('Table 31 covers spoilage, an item not put to fishers. Middlemen reported 5 kg (13, 59.1%) or 3 kg (9, 40.9%), the 5 kg share rising from 4 (36.4%) at Shimoni to all four (100.0%) at Vanga; the site difference approached but did not reach significance (p = .066). All five hoteliers reported 1 kg and all four exporters more than 10 kg.')
P('Read together, Tables 30 and 31 show a chain in which every actor loses stock and none records it against a shared standard. The actor holding live crabs carries the loss, and because no one measures it consistently the cost of mortality cannot be priced into a grade or recovered through one.')

H3('4.4.6 Payment, Price Setting and Sale Location')
TB(32, 'Mode of Payment by Actor and BMU')
P('As shown in Table 32, M-Pesa was the commonest single arrangement among fishers (30, 46.2%), but credit accounted for 18 (27.7%) and a further 7 (10.8%) combined M-Pesa with credit, so close to two fishers in five were paid at least partly on credit by the very middleman buying from them. Cash on delivery accounted for 10 (15.4%). Middlemen most often reported credit themselves (9, 40.9%), followed by M-Pesa (7, 31.8%) and cash on delivery (6, 27.3%). All five hoteliers used M-Pesa and cash together; the item was not completed by exporters. Payment was not associated with BMU for fishers (p = .515) or middlemen (p = .470).')
FG(23, 'Mode of Payment by Actor Category', 'f14_payment_actor',
   'Bars show the percentage within each actor category. The payment item was not completed by exporters.')
TB(33, 'Pricing Mechanism and How Prices Are Set by Actor and BMU')
P('Table 33 divides the chain in two. Not one respondent in any actor category, at any site, reported using a standard pricing mechanism. All 65 fishers and all five hoteliers described the price as fixed, meaning the buyer set it and told them; 14 of 22 middlemen (63.6%) and all four exporters described their own pricing as competitive. Price setting was not associated with BMU among middlemen (p = .722).')
FG(24, 'How Mud Crab Prices Are Set, by Actor Category', 'f15_pricesetting_actor',
   'Bars show the percentage within each actor category. Fishers and hoteliers described the price as fixed by the buyer; middlemen and exporters described their own pricing as competitive.')
TB(34, 'Factors Influencing Price Fluctuations and Location of Sale by Actor and BMU')
P('Table 34 shows that actors attributed price movement to different causes. All 65 fishers and all four exporters cited seasonal, weather and regulatory factors; 14 of 22 middlemen (63.6%) cited seasonal and economic factors; all five hoteliers cited seasonal factors alone. Location of sale divided by node: every fisher sold at the landing beach, while middlemen sold in town (11, 50.0%) or at a market (10, 45.5%), and hoteliers and exporters sold in town. Neither item was associated with BMU among middlemen (p = .238 and p = .928).')
P('Tables 32 to 34 describe the moment at which the terms of exchange are settled. The fisher sells at the beach, on the day, at a price the buyer sets, and is often paid at least partly in credit by that same buyer. Fixed at the fisher node and competitive at the middleman node are the same transaction described from either end.')

H3('4.4.7 Trading Relationships and Market Information')
TB(35, 'Tied Fishers, Tied Traders and Trading Agreements by Actor and BMU')
P('Table 35 shows that tied relationships run downward. No fisher had a fisher tied to him, yet every fisher had a trader tied to his business; 21 of 22 middlemen (95.5%) and all five hoteliers had fishers tied to theirs, while middlemen split evenly on whether they had tied traders (11 and 11). Formal or informal trading agreements covered 21 middlemen (95.5%) and every hotelier and exporter, against 1 of the 10 fishers who answered the item (10.0%).')
TB(36, 'Role of Intermediaries and Negotiation Terms by Actor and BMU')
P('As shown in Table 36, fishers saw the intermediary mainly as a negotiator (41, 63.1%) rather than a marketer (24, 36.9%); middlemen described their own role as negotiation and marketing together (14, 63.6%); hoteliers saw intermediaries as marketers and exporters as both. Terms were flexible for every fisher, middleman and hotelier, while all four exporters combined flexible terms with competitive bidding. Neither item was associated with BMU (p = .925 for fishers, p = 1.000 for middlemen).')
TB(37, 'Technology Adoption and Market Research by Actor and BMU')
P('Table 37 carries no variation at all, and is the more striking for it. Not one respondent in any actor category, at any site, had adopted modern equipment, and not one conducted market research. The figure was 0% on both items across all 96 respondents.')
P('Tables 35 to 37 close the functional account. In a chain where the buyer sets the price and controls the grading rule, no actor invests in equipment and no actor gathers independent market information. Every respondent said they kept up to date by networking, which means information travels along the same commercial relationships that determine the terms of trade.')

H3('4.4.8 Reported Mud Crab Prices')
P('Prices were collected for three size grades in Kenya shillings per kilogram of live crab. Every figure is a gross price at the point of sale; nothing was recorded about transport, holding, mortality, ice, packaging or the cost of money tied up between buying and selling.')
TB(38, 'Reported Mud Crab Prices by Actor Category and Size Grade')
P('As shown in Table 38, the large-crab price climbed at every step of the chain. Fishers averaged KSh 604.6 per kilogram, middlemen KSh 945.5, exporters KSh 1,700.0 and hoteliers KSh 2,200.0. Medium crabs ran KSh 514.6 for fishers and KSh 718.2 for middlemen, with exporters at KSh 1,300.0. Only fishers priced small crabs, averaging KSh 309.2; no middleman, hotelier or exporter reported a small-grade price at all, which points to the smallest crabs being absorbed locally rather than moving up the chain.')
TB(39, 'Kruskal–Wallis Comparisons of Reported Mud Crab Prices')
P('Table 39 tests those differences. The comparison across the four actor categories was significant for large crabs, H(3) = 55.84, p < .001, and for medium crabs, H(3) = 38.00, p < .001. Actor category therefore does influence the price received, at both grades for which more than one category reported a price. The small grade could not be compared across actors because only fishers reported it.')
FG(25, 'Mean Reported Mud Crab Price by Actor Category and Size Grade', 'f16_price_actor_grade',
   'Bars show the mean price in KSh per kilogram and error bars show ±1 standard deviation. Small-grade prices were reported only by fishers. The hotelier medium-grade mean of KSh 380 is discussed below.')
P('One value breaks the pattern. Hoteliers reported a mean of KSh 380.0 per kilogram for medium crabs, which is below the fisher price for the same grade and far below their own large-grade mean of KSh 2,200.0. All five records were retained exactly as entered. The figure may be correct if those entries refer to a different product form, unit or transaction, but it may equally be a field-entry problem. It is excluded from the chain calculation that follows and should be checked against the questionnaires before it is used to support any argument about value addition.')

H3('4.4.9 Marketing Margins and the Distribution of Value')
P('Reading the four node prices as one chain shows where the final price accumulates. Two end points were available: crabs that left the middleman for an exporter finished at KSh 1,700.0 per kilogram for the large grade, and crabs that went to a hotel kitchen finished at KSh 2,200.0. Expressing each node’s contribution as a share of that end price places all four actors on a single scale.')
TB(40, 'Marketing Margins and the Distribution of the Final Chain Price Across Actor Nodes')
P('As shown in Table 40, the fisher kept between a quarter and two fifths of the end price. Large crabs sold on to an exporter left 35.6% with the harvester; the same crabs sold on to a hotel left 27.5%. Medium crabs going for export were the fisher’s best case at 39.6%. In every chain the largest single share was added at the last step: 44.4% between the middleman and the exporter, 57.0% between the middleman and the hotel. The middleman, the actor most often identified with the low beach price, took the smallest share of the three, between 15.5% and 20.0%.')
FG(26, 'Share of the Final Chain Price Held at Each Actor Node, by Size Grade and Outlet', 'f17_chain_share',
   'Segments show the share of the end-of-chain price retained by the fisher, added between the fisher and the middleman, and added between the middleman and the final buyer. Shares sum to 100% within each bar. Because no cost data were collected these are gross price spreads and not net margins. The medium grade sold on to hoteliers is not shown, for the reason given above.')
P('Two qualifications belong with that result. The shares rest on group means from different respondents rather than on a single crab followed from beach to buyer, and they would shift once handling, freight and mortality were priced in. The direction is nevertheless hard to argue away. An exporter paying KSh 945.5 and selling at KSh 1,700.0 works on a spread of KSh 754.5 per kilogram, roughly one and a quarter times what the fisher received for landing the animal. This is the evidence Objective Two requires on how value is distributed: not that any actor takes more than their costs justify, which these data cannot show, but that the value is realised two steps beyond the point the harvester can reach.')

H3('4.4.10 Prices by Study Site')
P('Holding the actor role constant and comparing sites answers a different question: whether a fisher at one landing site receives a different price from a fisher at another.')
TB(41, 'Mean Reported Mud Crab Price by Actor Category, BMU and Size Grade')
P('Table 41 shows that fisher prices varied considerably by site. Majoreni fishers reported the highest large-crab mean at KSh 785.7 per kilogram, well above Shimoni at KSh 540.0 and Vanga at KSh 535.7, with Msambweni at KSh 650.0 on three respondents. Middleman means were much closer together, from KSh 857.1 at Majoreni to KSh 1,000.0 at Vanga. Returning to Table 39, fisher prices differed significantly across sites for large crabs, H(3) = 20.32, p < .001, and for medium crabs, H(3) = 20.07, p < .001, while middleman prices did not, H(2) = 5.33, p = .070 and H(2) = 3.78, p = .151. Small-grade prices did not differ across sites either, H(3) = 5.85, p = .119.')
FG(27, 'Mean Large-Crab Price by Actor Category and BMU', 'f18_price_site_actor',
   'Bars show the mean large-crab price in KSh per kilogram. A missing bar means no respondent of that actor category was sampled at that site. The single Shimoni hotelier and the Other sites group rest on very small numbers.')
TB(42, 'First-Sale Price Spread Between Fishers and Middlemen Within Each BMU')
P('Table 42 sets the two upstream node prices side by side at each landing site. Majoreni stands apart: its fishers held 91.7% of the local middleman price for large crabs and 91.3% for medium crabs, leaving spreads of only KSh 71.4 and KSh 57.1 per kilogram. At Shimoni and Vanga the same comparison gave 55.0% and 53.6% for large crabs, spreads of KSh 441.8 and KSh 464.3, or between 82% and 87% on top of what the fisher was paid. Vanga sat in between for medium crabs at 76.8%. The pattern holds in both grades, which makes it unlikely to be an artefact of one unusual price.')
FG(28, 'Fisher Price as a Percentage of the Middleman Price Within Each BMU', 'f19_fisher_share_site',
   'Bars show the fisher mean expressed as a percentage of the middleman mean for the same grade at the same site. A taller bar means a narrower gap between the two nodes. Msambweni and the Other sites group are absent because no middleman was sampled there.')
P('Where that difference comes from is worth stating plainly, because the two nodes did not move together. Fisher prices varied significantly across sites; middleman prices did not. The narrow Majoreni gap is therefore built on the fisher side of the transaction rather than on Majoreni traders charging less than their counterparts: Majoreni middlemen sold at KSh 857.1, within KSh 143 of the other two sites, while Majoreni fishers were paid KSh 785.7 against roughly KSh 537 at Shimoni and Vanga. The gap a fisher faces is set at his own landing site. It is also worth recalling from Table 19 that Majoreni fishers reached the point of sale fastest, which is consistent with, though not proof of, a shorter and more competitive first-sale market there.')

H3('4.4.11 Summary of Objective Two')
P('Objective Two asked what functions actors perform at each market node. Functions divided cleanly, and so did the information attached to them. Fishers harvested by hand, tied claws, packed into sacks, walked to the landing site and sold the whole catch to a first-level middleman at a price they called fixed. Middlemen aggregated, cleaned, sorted and graded on a four-criterion rule, then moved crabs by vehicle or boat to company agents, other middlemen or exporters. Hoteliers processed and froze for their own kitchens. Exporters packed Styrofoam for air freight under inspection and certification. Formal quality control, the fuller grading rule and contact with the final buyer sat entirely downstream.')
P('Prices rose at every node and differed significantly between actor categories. Expressed as shares of the price the crab eventually fetched, the fisher retained between 27.5% and 39.6%, the middleman added between 15.5% and 20.0%, and between 44.4% and 57.0% was added at the final buyer. Among fishers, price also differed significantly by site, and the size of the first-sale gap was set locally: Majoreni fishers held 91.7% of the middleman price for large crabs where Shimoni and Vanga fishers held close to 54%.')

H3('4.4.12 Discussion of Findings in Relation to Previous Studies')
P('The functional sequence documented here — harvesting, aggregation, processing and export, each performed by a distinct actor category — agrees closely with the value-chain structure described for the Kenyan mud crab fishery (Mirera, 2017a; Fondo & Ogutu, 2021) and with the broader account of small-scale fisheries chains in which middlemen supply the link between dispersed harvesters and distant buyers (Crona et al., 2016). The present study extends those accounts by testing each function against site rather than assuming uniformity: of the functional variables examined, only travel time to market, the large-crab size label and the small-crab size label showed a significant association with BMU among fishers, and none did among middlemen.')
P('The grading result is where this study makes its clearest contribution. Every actor graded, but fishers graded on weight alone while every downstream category used a four-criterion rule. Jacinto (2004) identifies precisely this kind of informational asymmetry as a determinant of how value is distributed in small-scale fisheries value chains, and the present data supply a clean instance of it in a fishery where the literature has so far documented actors and functions more thoroughly than the terms of exchange between them. The site variation in labelling adds a local dimension that earlier work has not reported.')
P('On handling and loss, the finding that protection rises downstream while mortality rises with the volume held is consistent with FAO (2025) on the determinants of survival and quality in the live mud crab trade. The divergence from that literature is not in the direction of the result but in its measurement: no actor in this chain recorded losses against a shared standard, so the cost of mortality cannot be attributed, priced or recovered. That is a gap in practice rather than a contradiction of previous findings.')
P('The price results agree with the expectation that later actors, carrying aggregation, mortality, transport and buyer-access costs, will trade at higher prices. The caveat matters and is stated plainly: these are gross prices. Munga and Muthumbi (2018) draw the same distinction for the Tana Delta mud crab fishery, where gross price differentials narrowed considerably once handling and transport were netted out, so nothing here should be read as a statement about profit.')
P('Within that limit, the distribution of the end-of-chain price is the substantive extension this study offers. The producer’s share of between 27.5% and 39.6% sits at the low end of what has been reported for perishable, high-value seafood. Jacinto (2004) argues that in small-scale fisheries the share captured at each node tracks control of information and market access more closely than physical effort, and the ordering here matches that argument exactly: the actor doing the fishing takes the smallest share, and the largest single share accrues at the step furthest from the water.')
P('The middleman result cuts against the popular account and deserves emphasis. Middlemen took the smallest of the three shares in every chain, between 15.5% and 20.0%, yet they are the actor fishers most often identify with the low beach price. Crona et al. (2016) reach a similar conclusion for Kenya and Zanzibar, finding middlemen widely blamed for outcomes largely determined further along the chain while themselves operating on modest turnovers and carrying the mortality risk. The present data support that reading rather than the popular one, and Table 30 documents the risk directly.')
P('Finally, the site contrast in the first-sale gap extends the literature on market integration. Green and Clark (2021) treat dispersion at the first point of sale as one of the more reliable indicators of weak market integration; on that criterion Shimoni and Vanga look the weaker markets of the three. Because fisher prices varied significantly across sites while middleman prices did not, the mechanism sits on the fisher side of the transaction. Two readings remain open — a less concentrated set of first buyers at Majoreni, or Majoreni traders being first-tier buyers reselling locally rather than consolidators shipping to Mombasa — and this study cannot separate them, because buyer concentration and onward destination were not measured at transaction level.')

json.dump(B, open('v5/ch4_obj2.json','w'), indent=1)
print('Objective Two blocks:', len(B), '| paragraphs:', sum(1 for b in B if b['k']=='p'),
      '| tables:', sum(1 for b in B if b['k']=='table'), '| figures:', sum(1 for b in B if b['k']=='fig'))
