# -*- coding: utf-8 -*-
"""Chapters Five and Six. Each objective is discussed as: key findings,
comparison with previous research, why they agree or differ, then theoretical
and practical implications. Every recommendation names the problem, the
evidence behind it, who should act and what outcome is expected."""
import json
B = []
def H1(t): B.append(dict(k='h1', t=t))
def H2(t): B.append(dict(k='h2', t=t))
def H3(t): B.append(dict(k='h3', t=t))
def H4(t): B.append(dict(k='h4', t=t))
def P(t):  B.append(dict(k='p', t=t))
def NL(t, r): B.append(dict(k='num', t=t, ref=r))
def BU(t): B.append(dict(k='bul', t=t))

H1('CHAPTER FIVE: DISCUSSION')

H2('5.1 Introduction')
P('This chapter interprets the findings of Chapter Four against the literature reviewed in Chapter Two. It takes the three objectives in turn, and each section sets out the key findings, compares them with previous research, explains where they agree and where they differ, and draws out the theoretical and practical implications. Section 5.5 brings the three objectives together under the structure-conduct-performance framework, and Section 5.6 states the limitations that bound every claim made here.')

# ---------------- OBJECTIVE ONE ----------------
H2('5.2 Objective One: Profile of Mud Crab Actors')
H3('5.2.1 Key Findings')
P('Four actor categories differed systematically and in the same direction on almost every measure. Fishers were younger, schooled to primary level or below, largely unlicensed, untrained, small-scale and un-diversified. Middlemen were older and far more experienced, with 72.7% carrying more than twenty years in the trade. Hoteliers and exporters held certificates, diplomas or degrees, were fully licensed, and operated at medium or large scale. Reported monthly income rose from KSh 8,969 among fishers to KSh 90,000 among exporters. No respondent in any category belonged to a cooperative, an association or a self-help group.')

H3('5.2.2 Gender and the Limits of the Sampling Frame')
P('Ninety-five of the 96 respondents were men, and the single woman was a hotelier rather than a harvester. The pattern is consistent with what has been reported along the Kenyan coast, where harvesting and much of the first-tier trade are male-dominated while women appear more often in processing, retail and culture activities (Mirera, 2014; Ochiewo et al., 2010).')
P('Why men dominate harvesting in this fishery is not something these data can settle, but the literature suggests three mechanisms that fit the setting. Mud crab harvesting in Kenya is done on foot in mangrove creeks at low spring tides, often at night and at a distance from the village, which carries mobility and safety costs that fall unequally on women (Mirera et al., 2013; Moser et al., 2005). Landing-site registers and BMU membership, the routes through which a harvester becomes visible to officials and buyers, have historically enrolled men. And the credit relationship documented in Chapter Four, in which a buyer advances cash against future supply, tends to run through established trading ties that new entrants do not have.')
P('The consequence for this study is methodological before it is substantive. Because the fisher sampling frame drew on landing-site registers, women working in processing, hospitality procurement, retail or crab fattening were unlikely to be reached. Ndanga et al. (2013) show that women in Kenyan aquaculture value chains concentrate precisely in the nodes that landing-site sampling does not cover, which is a plausible explanation for the pattern recorded here and a clear brief for future work. The finding should therefore be read as a description of the respondents reached, not as evidence that women are absent from the chain. Two practical openings follow: hospitality procurement and crab fattening are the nodes where women already appear in the regional literature, and both were named as opportunities by respondents in this study.')

H3('5.2.3 Experience, Licensing and the Absence of Collective Organisation')
P('Experience accumulated at the trading node rather than the harvesting node. This fits the account in Mirera et al. (2013), where local knowledge and repeated relationships shape how crabs are found, handled and moved, and it helps explain why middlemen reported regular buyers, competitive price setting and standing trading agreements while fishers did not. Crona et al. (2016) describe middlemen in Kenya and Zanzibar as a critical social-ecological link precisely because that accumulated relational knowledge is not easily replaced, and the present findings are consistent with that reading.')
P('The complete absence of collective membership is a more serious finding than a single percentage suggests. Groups are the normal vehicle for price information, savings, training, traceability and dealings with government, and the literature ties organised groups and local leadership to better fishery outcomes (Gutiérrez et al., 2011; Mirera, 2014). Without them, a fisher negotiates alone against a buyer with twenty years in the trade and knowledge of what crabs fetch further up the chain.')
P('Forming groups is not itself the remedy. Gutiérrez et al. (2011) found that leadership and clear incentives, rather than the existence of a group, separate the successful cases from the rest. That nothing at all exists here, at any node, suggests earlier attempts offered members nothing they could see. Any group formed in response to this study would need a commercial purpose, transparent leadership and a service members can point to.')

H3('5.2.4 Credit and Dependence Within the Chain')
P('No fisher used a formal loan, yet 93.8% named a middleman as their main source of credit, and close to two fishers in five were paid at least partly on credit by the buyer purchasing from them. Crona et al. (2016) describe such arrangements as enabling and constraining at once: the advance solves this week’s cash problem while narrowing where the fisher can sell. Béné et al. (2007) make a similar point about small-scale fisheries generally, treating informal credit as both safety net and mechanism of persistent low returns.')
P('Which of the two dominates here cannot be judged from this study, because amounts, terms and duration went unrecorded. What can be said is that the person extending the credit is the same person setting the price the fisher calls fixed, and that no alternative source of working capital was reported at the harvesting node. That combination is what gives the relationship its force.')

H3('5.2.5 Implications')
P('Theoretically, the profile results support treating actor category rather than location as the primary structural variable in this market. Differences between fishers, middlemen, hoteliers and exporters were large and consistent, while differences between landing sites were fewer and confined mostly to fishers. A market-structure account of this fishery is therefore an account of nodes, not of places.')
P('Practically, the results identify three entry points that do not require new infrastructure: a licensing route that upstream actors can actually complete, a source of working capital that is not the buyer, and a collective body with a service attached. Each addresses a condition documented in Chapter Four rather than a general aspiration.')

# ---------------- OBJECTIVE TWO ----------------
H2('5.3 Objective Two: Functions at Each Market Node and the Distribution of Value')
H3('5.3.1 Key Findings')
P('Functions divided cleanly by node and so did the information attached to them. Fishers harvested, tied claws, packed in sacks and walked to the landing site. Middlemen aggregated, cleaned, sorted and graded on a four-criterion rule and moved crabs by vehicle or boat. Hoteliers processed and froze. Exporters packed Styrofoam under inspection and certification. Prices rose at every node, differed significantly between actor categories, and among fishers differed by site as well.')

H3('5.3.2 Grading as a Mechanism of Value Capture')
P('Every actor said they graded. They did not grade by the same rule. All 65 fishers used weight alone, while 95.5% of middlemen and every hotelier and exporter combined size, weight, shell condition and claw size. Jacinto (2004) identifies exactly this kind of informational asymmetry as a determinant of how value is distributed in small-scale fisheries value chains, and the present data supply a clean instance of it.')
P('The site variation in grading language reinforces the point. At Shimoni, 44.0% of fishers described their large category as mixed and 36.0% did the same for the small category, while fishers at the other three sites used the plain labels, χ²(3, N = 63) = 16.87, p = .001 and χ²(3, N = 63) = 15.96, p = .002. The survey recorded the label, not a measured carapace width, so this is vocabulary rather than biology. It carries a practical cost all the same: a Shimoni fisher and his buyer may not mean the same thing by the word large, and that is the condition under which a grading dispute goes the better-informed party’s way.')

H3('5.3.3 Handling, Packaging and Loss')
P('Packaging became more protective downstream, from sacks to crates to Styrofoam, and reported mortality rose with the volume each actor held. Survival and product quality in the live mud crab trade turn on handling, containment and transport conditions (FAO, 2025). The absence of formal quality control among fishers and middlemen does not mean no care was taken; fishers tied claws and middlemen cleaned and sorted. The weakness is that neither procedures nor losses were documented against a shared standard, so the cost of mortality cannot be priced into a grade or recovered through it.')

H3('5.3.4 Price Formation and the Distribution of Value')
P('Reported prices rose at every node and the actor comparisons were unambiguous, H(3) = 55.84, p < .001 for large crabs and H(3) = 38.00, p < .001 for medium crabs. Rising prices are expected where later actors carry aggregation, mortality, transport, packaging and buyer-access costs. The caveat matters and is stated plainly: these are gross prices. Munga and Muthumbi (2018) draw the same distinction for the Tana Delta mud crab fishery, where gross price differentials narrowed considerably once handling and transport were netted out, so nothing in this section should be read as a statement about profit.')
P('Within that limit, expressing each node’s price as a share of the end-of-chain price answers the question of how value is distributed. A large crab reaching an exporter left 35.6% of its final price with the fisher, 20.0% at the middleman step and 44.4% at the exporter step. The same crab reaching a hotel kitchen left the fisher 27.5% and the hotel 57.0%. Medium crabs bound for export were the fisher’s best case at 39.6%. The producer’s share of the final price is a standard measure of marketing performance, and values in this range sit at the low end of what has been reported for perishable, high-value seafood. Jacinto (2004) argues that in small-scale fisheries the share captured at each node tracks control of information and market access more closely than it tracks physical effort, and the ordering here matches that: the actor doing the fishing takes the smallest share, and the largest single share accrues at the step furthest from the water.')
P('The middleman result deserves emphasis because it cuts against the usual account. Middlemen took the smallest of the three shares in every chain, between 15.5% and 20.0%, yet they are the actor fishers most often identify with the low beach price. Crona et al. (2016) reach a similar conclusion for Kenya and Zanzibar, finding that middlemen are widely blamed for outcomes largely determined further along the chain while themselves operating on modest turnovers and carrying the mortality risk. The present data support that reading rather than the popular one, and Chapter Four documents the risk directly: 95.5% of middlemen reported daily mortality of 4 to 5 kg against 0.5 to 1 kg among fishers.')

H3('5.3.5 Site Differences and What Drives Them')
P('The actor comparison and the site comparison answer different questions, and keeping them apart was necessary. Compare sites without holding the actor constant and a site with more middlemen looks like a high-price site purely because of its respondent mix. With the role held constant, fisher prices differed significantly across sites for large crabs, H(3) = 20.32, p < .001, and medium crabs, H(3) = 20.07, p < .001, while middleman prices did not, H(2) = 5.33, p = .070 and H(2) = 3.78, p = .151.')
P('That asymmetry produced the study’s sharpest single contrast. At Majoreni the fisher price stood at 91.7% of the local middleman price for large crabs and 91.3% for medium crabs, spreads of KSh 71.4 and KSh 57.1 per kilogram. At Shimoni and Vanga the same figures were 55.0% and 53.6% for large crabs, spreads of KSh 441.8 and KSh 464.3. Because fisher prices varied across sites and middleman prices did not, the narrow Majoreni gap is built on the fisher side: Majoreni traders sold at KSh 857.1, within KSh 143 of the other two sites, while Majoreni fishers were paid KSh 785.7 against roughly KSh 537 elsewhere.')
P('Two readings fit. Majoreni fishers may face a less concentrated set of first buyers, so competition at the beach lifts the first-hand price; or the seven middlemen sampled there may be first-tier buyers reselling locally rather than consolidators shipping to Mombasa, in which case their price is a shorter step from the water and the comparison is not quite like for like. This study cannot separate the two, since buyer concentration and onward destination were not measured at transaction level. Green and Clark (2021) treat dispersion at the first point of sale as one of the more reliable indicators of weak market integration, and on that criterion Shimoni and Vanga look the weaker markets of the three. The practical implication is unchanged by which reading is correct: the terms a fisher gets are settled at their own landing site.')

H3('5.3.6 The Hotelier Medium-Grade Anomaly')
P('The hotelier medium-grade mean of KSh 380.0 per kilogram does not fit the pattern. It is below the fisher price for the same grade and far below the same respondents’ large-crab mean of KSh 2,200.0. Two explanations are plausible. The entries may refer to a different product form, unit or transaction, such as a processed portion rather than live weight, in which case the value is correct but not comparable with the others. Alternatively it may be a field-entry error. The values were retained to preserve fidelity to the source data and excluded from the chain calculation, but they should be confirmed against the questionnaires before being used to support any argument about value addition at the hospitality node.')

H3('5.3.7 Implications')
P('Theoretically, these results locate the mechanism of value capture in control of the grading rule and of the connection to the final buyer, rather than in harvesting effort or in the middleman’s margin. That is the specific contribution this study makes to the value-chain literature on Kenyan mud crabs, which has so far documented actors and functions more thoroughly than the distribution of returns among them.')
P('Practically, two interventions follow directly from the numbers and neither requires capital investment: a written grading standard that both parties to a first sale can read, and an independent record of what grades are fetching. Both attack the informational asymmetry the data identify rather than the price level, which no intervention in this study’s reach can set.')

# ---------------- OBJECTIVE THREE ----------------
H2('5.4 Objective Three: Constraints and Opportunities')
H3('5.4.1 Key Findings')
P('No constraint was shared across the chain. Fishers named price fluctuation and poor roads, middlemen mortality and the lack of aggregation facilities, hoteliers seasonality, exporters freight cost and flight delays. Barriers to market access were reported by 95.8% of respondents. No actor had adopted new equipment or conducted market research. Most respondents judged the market poorly structured, and management-plan awareness reached 95.5% of middlemen and every exporter but only 15.4% of fishers and no hotelier.')

H3('5.4.2 Constraints Follow Function')
P('Each constraint follows from the work the actor does. The fisher sells the same day at a price he does not set, so volatility reaches him first. The middleman holds stock, so he loses crabs; mortality was named by half of them and all four Vanga middlemen. The hotelier lives on tourist arrivals and feels the season. The exporter lives on cargo space and feels the freight. One chain-wide intervention will not reach all four, which is why the recommendations in Chapter Six are written by actor category.')
P('The infrastructure answers point the same way. Poor roads dominated the fisher responses at 98.5% while 90.9% of middlemen named the lack of aggregation facilities. Better access routes would improve movement from landing areas but would not reduce holding losses; aggregation facilities would improve shade, loading and live-crab management but would not widen fisher buyer choice unless linked to transport and price information. Infrastructure planning therefore has to connect landing-site access with holding and distribution needs, not choose between them.')

H3('5.4.3 Governance and the Direction Information Travels')
P('Negative views of market organisation sit comfortably with everything else recorded here: no collective membership, low upstream licensing, informal grading, no market research and fixed prices reported by every fisher. Awareness of the crab fishery management plan followed commercial position rather than geography. Information moves along commercial relationships instead of through the co-management structures built to carry it.')
P('Beach Management Units remain the most practical institutions for narrowing that gap. Njiru et al. (2021) found that socioeconomic factors influence trader participation in BMUs in Kwale County, which supports communication designed for specific actor groups rather than a single general announcement. The large neutral response among fishers on the existence of a policy framework should not be read as approval; set beside 15.4% management-plan awareness, it more likely reflects unfamiliarity.')

H3('5.4.4 Opposing Priorities Within One Transaction')
P('Fishers chose market-access improvement, 86.2% of them, while middlemen chose price stability, 95.5%. These are two views of one exchange. The fisher wants an alternative to the buyer standing in front of him; the middleman wants the price he pays and receives to hold still while he carries stock and credit risk. Splitting the difference will not reconcile them, because better market access for fishers means more competition for middlemen. Better price information and clearer grades reduce uncertainty for both without fixing an administered price.')
P('Reported youth involvement was low or very low throughout, even though more than half the fishers were aged 18 to 35 and four were under 18. Respondents may have understood youth involvement as formal participation, commitment or ownership rather than presence in the fishery. Future questionnaires should define the concept directly, and the presence of minors in harvesting raises safeguarding and schooling questions this study was not designed to answer but should not pass over.')

H3('5.4.5 Implications')
P('Theoretically, the constraint results show that performance in this chain is bounded at different points for different actors, which is an argument against treating the value chain as a single system with one binding constraint. Practically, they mean that an intervention budget spent uniformly across nodes will be largely wasted, and that the sequence in which interventions are attempted matters as much as their content.')

H2('5.5 Synthesis Using the Structure-Conduct-Performance Framework')
P('Set against the structure-conduct-performance framework that guided this study, the three objectives describe a single system. The structure is concentrated at the point of first sale. Many small, unorganised sellers face a smaller number of better-capitalised buyers; entry downstream requires licences, capital and buyer contacts that upstream actors do not have; and no collective body exists at any node to pool bargaining power.')
P('Conduct follows from that structure. Buyers set prices and every fisher in the sample accepted them as fixed. Grading runs on a rule only the buyer fully controls. Credit advances tie sellers to particular buyers. Nobody conducts market research, so information travels through the same commercial relationships that set the prices in the first place.')
P('Performance is what that structure and conduct would predict. Reported monthly income ran from KSh 8,969 among fishers to KSh 90,000 among exporters. The fisher’s share of the end-of-chain price ran between 27.5% and 39.6%, and the largest single share in every chain accrued at the node furthest from the water. Price dispersion was wide at the harvesting node and narrow after aggregation, which Green and Clark (2021) treat as a signature of weak integration at the first point of sale. Losses were reported everywhere and measured nowhere against a common standard. Value addition happened almost entirely downstream, and the actors doing it were the same ones defining the grades and setting the prices.')
P('This has a practical edge. Interventions aimed only at production, better gear or bigger catches, are unlikely to shift how value is distributed here, because the binding constraint is not how many crabs come ashore but the terms on which they change hands. Three things decide those terms: the grading rule, whether a fisher has any independent price information, and the credit relationship. All three operate in the moment a fisher hands his catch to a first-level middleman.')

H2('5.6 Study Limitations')
P('The sample was not fully probabilistic. Reliable lists were unavailable for middlemen, hoteliers and exporters, so referral and convenience procedures were used downstream, and the findings describe the respondents reached rather than population estimates for all Kwale County mud crab actors. The achieved fisher sample of 65 fell short of the calculated target of 83, a coverage rate of 78.3%, and the 18 fishers not reached may differ from those interviewed.')
P('Snowball sampling may over-represent actors with stronger trading connections and under-represent isolated or informal operators, so the middleman and exporter findings in particular should be read with that in mind. Only five hoteliers and four exporters were sampled, no middleman was sampled at Msambweni, and only three fishers were interviewed there, which limits site-level precision.')
P('The design was cross-sectional and covered a single survey period, so seasonal variation in price, catch and mortality is not captured and no causal direction can be established. Prices, income and losses were self-reported and were not verified against transaction records. Sixty-eight categorical tests were run without a correction for multiple comparisons, so associations with probabilities close to .05 should be treated as exploratory. Finally, the survey did not collect the transaction-level cost, volume and mortality data needed to convert gross price differences into net margins, which is why this study describes how value is distributed but not how profit is distributed.')

# ---------------- CHAPTER SIX ----------------
H1('CHAPTER SIX: CONCLUSIONS AND RECOMMENDATIONS')

H2('6.1 Introduction')
P('This chapter draws conclusions from the three objectives and sets out recommendations. Each recommendation names the problem identified in Chapter Four, the evidence behind it, the body best placed to act and the outcome that would show it had worked. Recommendations that the data cannot support are not made.')

H2('6.2 Conclusions')
H3('6.2.1 Conclusion for Objective One')
P('The four actor categories differ systematically and in the same direction on almost every characteristic measured. Fishers are younger, schooled to primary level or below, small-scale, minimally licensed, untrained and un-diversified, and they borrow from the same middlemen who buy from them. Middlemen are older, far more experienced and better capitalised. Hoteliers and exporters are formally qualified, fully licensed and operating at a scale upstream actors do not reach. No respondent in any category belonged to a cooperative, an association or a self-help group. Study site mattered for the age of the fishing population, for marital status and for training, but the larger and more consistent differences were between actor categories.')
H3('6.2.2 Conclusion for Objective Two')
P('The chain runs as a clear functional sequence from harvesting through aggregation to processing and export, and the information used to assign value is concentrated downstream. Fishers graded on weight alone while every other category used a four-criterion rule; formal quality control and contact with the final buyer sat entirely downstream. Reported prices rose significantly at each node. Expressed as shares of the price the crab eventually fetched, the fisher retained between 27.5% and 39.6%, the middleman added between 15.5% and 20.0%, and between 44.4% and 57.0% was added at the final buyer. The size of the first-sale gap was set locally: Majoreni fishers held 91.7% of the middleman price for large crabs where Shimoni and Vanga fishers held close to 54%, and that difference came from variation in what fishers were paid rather than from what traders charged. What determines the price of a crab in this fishery is position in the chain, control of the grading rule and access to alternative buyers, not harvesting effort.')
H3('6.2.3 Conclusion for Objective Three')
P('Constraints arise at different points in the chain and follow the work each actor does: unstable prices and poor roads for fishers, mortality and inadequate aggregation facilities for middlemen, seasonality for hoteliers, freight cost and flight risk for exporters. Barriers to market access were close to universal, no actor had adopted new equipment or conducted market research, and most respondents regarded the market as poorly structured. Management-plan awareness reached traders and exporters while missing fishers and hoteliers. Improvement therefore requires coordinated but actor-specific measures rather than one intervention applied uniformly across all nodes.')

H2('6.3 Overall Conclusion')
P('The South Coast mud crab market is commercially active and institutionally uneven. Fishers supply the product with almost no institutional support behind them, while middlemen and downstream actors hold the grading, the logistics and the connection to high-value buyers. Study site matters for the age of the fishing population, for the words used to describe grades, for the price fishers receive and for the constraint middlemen name, but the larger and steadier divide runs between market nodes rather than between places. Improvement should start where the terms of exchange are set: a shared grading standard, a price record that is reliable and public, better live-crab handling, infrastructure aimed at both ends of the chain, licensing people can actually obtain, and communication that reaches harvesters as dependably as it now reaches traders.')

H2('6.4 Recommendations')
P('Each recommendation below states the problem, the evidence from Chapter Four, the actor responsible and the outcome that would demonstrate success.')

H3('6.4.1 Recommendations From Objective One')
NL('Problem: upstream actors are largely outside the formal system. Evidence: 12.5% of fishers and 27.3% of middlemen held an operating licence, against every hotelier and exporter. Action: the county fisheries department and BMU committees should run registration and licensing clinics at Shimoni, Majoreni, Vanga and Msambweni, explaining fees, documents, benefits and renewal in plain language and helping applicants complete the forms on the day. Expected outcome: licensed fisher and middleman numbers rise measurably at the four sites within two licensing cycles.', 'n1')
NL('Problem: fishers depend on their buyers for working capital. Evidence: no fisher used a formal loan, yet 93.8% named a middleman as their main source of credit, and 38.5% were paid at least partly on credit by the buyer purchasing from them. Action: financial institutions, development partners and buyers should separate formal working-capital lending from buyer advances, and any advance should carry written terms stating amount, repayment method, duration, any deduction and whether exclusive supply is a condition. Expected outcome: fishers can state the terms of their own credit, and the share reporting a middleman as their only source of capital falls.', 'n1')
NL('Problem: no collective body exists at any node. Evidence: 0 of 96 respondents belonged to a cooperative, an association or a self-help group. Action: BMUs and the county should support voluntary groups that start from one concrete service, such as a shared price register, a savings facility or bulk purchase of containers, with accountable leadership and records open to members. Expected outcome: at least one functioning group per BMU that members can name a benefit from after twelve months.', 'n1')
NL('Problem: training does not reach harvesters. Evidence: 7.7% of fishers had received formal mud crab training, and training differed significantly across sites, χ²(3, N = 63) = 8.48, p = .035. Action: extension officers should deliver practical BMU-level training in grading, live-crab handling, record keeping, simple cost calculation and buyer negotiation, pitched to the younger fisher profile at Shimoni and the older profile at Majoreni. Expected outcome: measurable improvement in grading accuracy and reported handling practice at the trained sites.', 'n1')
NL('Problem: women and young people are invisible in the evidence base. Evidence: 95 of 96 respondents were men and the sampling frame drew on landing-site registers. Action: future actor mapping by the county and by researchers should deliberately include processing, hospitality procurement, retail and crab fattening, and safeguarding procedures are required wherever respondents younger than 18 participate in harvesting. Expected outcome: a Kwale actor register that records the nodes where women work, and a stated safeguarding policy covering minors in the fishery.', 'n1')

H3('6.4.2 Recommendations From Objective Two')
NL('Problem: fishers cannot verify the grade they are offered. Evidence: all 65 fishers graded on weight alone while 95.5% of middlemen and every hotelier and exporter used size, weight, shell condition and claw size. Action: BMUs, fisheries officers and buyers should agree one grading sheet for Grades A, B and C giving weight ranges and visible quality criteria, displayed at the point of sale with the price offered for each grade, and taught with sample crabs. Expected outcome: fishers and buyers describe the same crab with the same grade, and the share of fishers recording mixed grades falls from the current 23.1% for large crabs.', 'n2')
NL('Problem: grading vocabulary is not shared across sites. Evidence: large-crab and small-crab size labels differed significantly across sites among fishers, χ²(3, N = 63) = 16.87, p = .001 and χ²(3, N = 63) = 15.96, p = .002, with 44.0% of Shimoni fishers using mixed labels. Action: the same grading terms should be adopted across all four BMUs rather than left to local usage. Expected outcome: site differences in label use narrow at the next survey round.', 'n2')
NL('Problem: fishers have no independent price reference. Evidence: every fisher described the price as fixed by the buyer, no actor conducted market research, and fisher large-crab prices ranged from KSh 535.7 at Vanga to KSh 785.7 at Majoreni, a spread of 47%. Action: each BMU should keep a weekly price register by grade, buyer and site, publishing the median and the observed range rather than a guaranteed price. Expected outcome: dispersion in first-sale prices across sites narrows, and fishers can quote a reference price when negotiating.', 'n2')
NL('Problem: value is realised where the harvester cannot reach. Evidence: the fisher retained 27.5% to 39.6% of the end-of-chain price while 44.4% to 57.0% was added at the final buyer. Action: BMUs and the county should test one direct-supply arrangement between an organised fisher group and a hotel or exporter, with agreed grades, volumes and payment terms. Expected outcome: participating fishers receive a measurably higher share of the end price than the site baseline recorded here.', 'n2')
NL('Problem: live-crab losses are carried but not measured. Evidence: fishers reported 0.5 to 1 kg of daily mortality, 95.5% of middlemen reported 4 to 5 kg, and no actor kept records against a common standard. Action: BMUs should pilot aggregation and live-holding facilities with shade, ventilation, secure reusable containers, safe loading space and a simple mortality log, and should test reusable ventilated containers against sacks under normal trading conditions. Expected outcome: recorded mortality per consignment falls and the container trial produces a cost per kilogram saved.', 'n2')
NL('Problem: five hotelier medium-grade price records are inconsistent with every other node. Evidence: a hotelier mean of KSh 380.0 per kilogram sits below the fisher price for the same grade and far below the same respondents’ large-crab mean of KSh 2,200.0. Action: the candidate should check these five records against the original questionnaires and field notes to confirm unit, product form and transaction context. Expected outcome: the records are either corrected or confirmed, and the basis of the hospitality price is documented before any value-addition estimate uses it.', 'n2')

H3('6.4.3 Recommendations From Objective Three')
NL('Problem: infrastructure constraints differ by node. Evidence: 98.5% of fishers named poor roads while 90.9% of middlemen named the lack of aggregation facilities. Action: the county should prepare one actor-specific infrastructure plan covering access routes and landing facilities for fishers, aggregation and holding facilities for middlemen, demand coordination for hotels and freight-risk planning for exporters. Expected outcome: a costed plan in which each investment names the actor category it serves and the constraint it removes.', 'n3')
NL('Problem: management information reaches traders and misses harvesters. Evidence: 95.5% of middlemen and every exporter knew of a crab fishery management plan, against 15.4% of fishers and no hotelier. Action: BMUs and fisheries officers should target management-plan communication at fishers and hoteliers first, record who received it and check understanding rather than counting attendance. Expected outcome: fisher awareness rises substantially above the current 15.4% at the next survey round.', 'n3')
NL('Problem: price instability is the dominant complaint but an administered price is not supportable. Evidence: price fluctuation was the main constraint for 90.8% of fishers and half the middlemen, while 95.5% of middlemen named price stability as their priority. Action: county and national agencies should address stability through reliable information, consistent grading, predictable payment terms and buyer competition rather than a guaranteed price, which these data do not support and which no institution in the chain could currently enforce. Expected outcome: reported price uncertainty falls without an administered price being introduced.', 'n3')
NL('Problem: diversification is named as an opportunity but is untested. Evidence: diversification was the only risk-management method reported by fishers, middlemen and hoteliers, yet no respondent had adopted an innovative response and most fishers rated diversification potential negative or unexplored. Action: development partners and the county should run small, costed diversification pilots such as crab fattening, each linked to a confirmed buyer, with participation terms and cost-sharing agreed before investment. Expected outcome: each pilot reports survival, feed and labour costs and a realised price, so the next round can be judged on evidence.', 'n3')
NL('Problem: youth participation is rated low across the chain while minors work in harvesting. Evidence: every respondent expressing a view rated youth involvement low or very low, yet 53.8% of fishers were aged 18 to 35 and four were under 18. Action: county youth and fisheries programmes should combine technical training with supervised market access, savings or credit and mentorship, define youth participation explicitly in any monitoring tool, and include safeguards for minors. Expected outcome: a defined youth participation measure is reported at the next survey and safeguarding cases are handled under a stated procedure.', 'n3')

H2('6.5 Recommendations for Further Research')
BU('Collect transaction-level price, quantity, grade, cost and mortality data across high and low seasons so that net marketing margins can be estimated rather than the gross price spreads reported here. This is the single most important gap in the present study.')
BU('Repeat the survey with probability sampling wherever reliable actor lists can be built, ensuring that each target BMU contributes both fisher and middleman observations so that site comparisons rest on comparable samples.')
BU('Oversample hoteliers, exporters, women and young people so that downstream functions and under-represented participants can be analysed with the precision the present sample does not allow.')
BU('Measure buyer concentration and onward destination at transaction level, which would separate the two explanations offered here for the narrow first-sale gap recorded at Majoreni.')
BU('Use qualitative interviews to clarify buyer advances, loan terms, tied-supply relationships, grading disputes and the reasons actors regard the market as poorly structured.')
BU('Evaluate the price-register, grading-sheet and container pilots recommended in Section 6.4 with before-and-after measures of price dispersion, mortality and fisher bargaining outcomes, treating them as interventions to be tested rather than improvements to be assumed.')

json.dump(B, open('v5/ch56_base.json','w'), indent=1)
print('Chapters Five and Six blocks:', len(B), '| paragraphs:', sum(1 for b in B if b['k']=='p'))
