# -*- coding: utf-8 -*-
"""D-efficient design for the childcare DCE, generated by coordinate exchange.

Zero priors, so choice probabilities are uniform and the MNL information matrix
is exact:  I = sum_s X_s' (diag(p) - p p') X_s  with p = 1/J.
Maximising det(I) is therefore a well-defined, checkable optimisation.
"""
import numpy as np, itertools, json

rng = np.random.default_rng(20260918)

# ---- attributes: levels listed best-first where the attribute has an order ----
ATTRS = [
    ("cost", ["KES 30/day", "KES 60/day", "KES 100/day", "KES 150/day"], True),
    ("location", ["Inside the market, next to the stalls", "5-minute walk",
                  "15-minute walk"], True),
    ("hours", ["6:00–19:00", "7:00–17:00"], True),
    ("care", ["1 trained caregiver per 5 children",
              "1 trained caregiver per 10 children",
              "1 untrained helper per 10 children"], True),
    ("food", ["Porridge and lunch provided", "You bring the child's food"], True),
    ("operator", ["County staff; complaints go to the county office",
                  "Private operator paying rent; operator sets fees; "
                  "complaints go to the operator",
                  "County and private operator jointly agree fees; "
                  "complaints go to a joint office",
                  "Committee of market traders; complaints go to the committee"],
     False),
    ("inclusion", ["Physically accessible with staff trained to support children "
                   "with disabilities",
                   "Physically accessible (ramp, adapted toilet), staff not "
                   "disability-trained",
                   "No special accommodation for children with disabilities"], True),
]
NAMES   = [a[0] for a in ATTRS]
LEVELS  = [a[1] for a in ATTRS]
ORDERED = [a[2] for a in ATTRS]
LVLS    = np.array([len(l) for l in LEVELS])
NA      = len(ATTRS)

N_SETS, SPR = 18, 6
N_BLOCKS = N_SETS // SPR
K = int((LVLS - 1).sum()) + 1          # dummies + one opt-out constant
OFFSETS = np.concatenate([[0], np.cumsum(LVLS - 1)])

def row(alt):
    """Dummy-coded row for an alternative (list of level indices). Level 0 = reference."""
    x = np.zeros(K)
    for j, lv in enumerate(alt):
        if lv > 0:
            x[1 + OFFSETS[j] + lv - 1] = 1.0
    return x

OPTOUT = np.zeros(K); OPTOUT[0] = 1.0   # constant only

P = np.full(3, 1/3)
W = np.diag(P) - np.outer(P, P)

def set_info(a, b):
    X = np.vstack([row(a), row(b), OPTOUT])
    return X.T @ W @ X

def det_info(design):
    I = np.zeros((K, K))
    for a, b in design:
        I += set_info(a, b)
    return np.linalg.slogdet(I)

def d_error(design):
    sign, logdet = det_info(design)
    if sign <= 0:
        return np.inf
    return float(np.exp(-logdet / K))

# ---- constraints -------------------------------------------------------------
MIN_DIFF = 4          # at least this many of the 7 attributes must differ

def dominated(a, b):
    """True if one alternative is weakly better on every ordered attribute and
    strictly better on at least one, with the unordered attribute held equal.
    Such a card asks the respondent to make no trade-off at all."""
    for x, y in ((a, b), (b, a)):
        same_unordered = all(x[j] == y[j] for j in range(NA) if not ORDERED[j])
        if not same_unordered:
            continue
        idx = [j for j in range(NA) if ORDERED[j]]
        if all(x[j] <= y[j] for j in idx) and any(x[j] < y[j] for j in idx):
            return True
    return False

def valid(a, b):
    if sum(x != y for x, y in zip(a, b)) < MIN_DIFF:
        return False
    return not dominated(a, b)

def random_set():
    while True:
        a = [int(rng.integers(L)) for L in LVLS]
        b = [int(rng.integers(L)) for L in LVLS]
        if valid(a, b):
            return [a, b]

# ---- coordinate exchange -----------------------------------------------------
def optimise(n_start=40, max_pass=30):
    best, best_err = None, np.inf
    for _ in range(n_start):
        design = [random_set() for _ in range(N_SETS)]
        err = d_error(design)
        for _ in range(max_pass):
            improved = False
            for s in range(N_SETS):
                for alt in (0, 1):
                    for j in range(NA):
                        cur = design[s][alt][j]
                        for lv in range(LVLS[j]):
                            if lv == cur:
                                continue
                            design[s][alt][j] = lv
                            if not valid(design[s][0], design[s][1]):
                                design[s][alt][j] = cur
                                continue
                            e = d_error(design)
                            if e < err - 1e-12:
                                err, cur, improved = e, lv, True
                            else:
                                design[s][alt][j] = cur
            if not improved:
                break
        if err < best_err:
            best, best_err = [[a[:], b[:]] for a, b in design], err
    return best, best_err

design, err = optimise()
print(f"D-error: {err:.6f}   (lower is better)")

# ---- blocking: split so level frequencies are as even as possible ------------
def imbalance(assign):
    tot = 0
    for j in range(NA):
        counts = np.zeros((N_BLOCKS, LVLS[j]))
        for s, blk in enumerate(assign):
            for alt in (0, 1):
                counts[blk, design[s][alt][j]] += 1
        tot += np.abs(counts - counts.mean(axis=0)).sum()
    return tot

best_assign, best_imb = None, np.inf
base = np.repeat(np.arange(N_BLOCKS), SPR)
for _ in range(20000):
    a = rng.permutation(base)
    v = imbalance(a)
    if v < best_imb:
        best_assign, best_imb = a.copy(), v
print(f"Block imbalance: {best_imb:.1f}  (0 = perfectly even)")

# ---- verification ------------------------------------------------------------
print("\nChecks")
print("  identical A/B pairs:",
      sum(design[s][0] == design[s][1] for s in range(N_SETS)))
print("  dominated pairs    :",
      sum(dominated(design[s][0], design[s][1]) for s in range(N_SETS)))
diffs = [sum(x != y for x, y in zip(design[s][0], design[s][1])) for s in range(N_SETS)]
print(f"  attributes differing per card: min {min(diffs)}, max {max(diffs)}, "
      f"mean {np.mean(diffs):.1f}")

print("\nLevel counts across all 36 alternatives")
for j, nm in enumerate(NAMES):
    counts = [sum(design[s][alt][j] == lv for s in range(N_SETS) for alt in (0, 1))
              for lv in range(LVLS[j])]
    print(f"  {nm:<10} {counts}   (even would be {36/LVLS[j]:.1f} each)")

print("\nOperator level by block")
for blk in range(N_BLOCKS):
    counts = [sum(design[s][alt][5] == lv for s in range(N_SETS)
                  for alt in (0, 1) if best_assign[s] == blk)
              for lv in range(LVLS[5])]
    print(f"  Block {blk+1}: {counts}")

out = {"levels": {n: l for n, l in zip(NAMES, LEVELS)},
       "d_error": err,
       "sets": [{"set": s + 1, "block": int(best_assign[s]) + 1,
                 "A": {NAMES[j]: LEVELS[j][design[s][0][j]] for j in range(NA)},
                 "B": {NAMES[j]: LEVELS[j][design[s][1][j]] for j in range(NA)}}
                for s in range(N_SETS)]}
out["sets"].sort(key=lambda r: (r["block"], r["set"]))
with open('/home/user/python/output/r/dce_design_cards.json', 'w') as f:
    json.dump(out, f, indent=1, ensure_ascii=False)
print("\nwrote dce_design_cards.json")
